import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const CORPORATE_BONDS = [
  {
    ticker: "YCA6O",
    issuer: "YPF S.A.",
    currency: "USD",
    law: "NY",
    couponRate: 0.085,
    couponFrequency: 2,
    firstCouponDate: "2024-01-15",
    maturityDate: "2029-01-15",
    amortizationType: "bullet",
    minDenomination: 1000,
    creditRating: "A(arg)",
  },
  {
    ticker: "YMCHO",
    issuer: "YPF S.A.",
    currency: "USD",
    law: "NY",
    couponRate: 0.0875,
    couponFrequency: 2,
    firstCouponDate: "2024-03-15",
    maturityDate: "2031-03-15",
    amortizationType: "bullet",
    minDenomination: 1000,
    creditRating: "A(arg)",
  },
  {
    ticker: "YMCIO",
    issuer: "YPF S.A.",
    currency: "USD",
    law: "NY",
    couponRate: 0.069,
    couponFrequency: 2,
    firstCouponDate: "2025-01-17",
    maturityDate: "2029-07-17",
    amortizationType: "bullet",
    minDenomination: 1000,
    creditRating: "A(arg)",
  },
  {
    ticker: "PNDCO",
    issuer: "Pan American Energy",
    currency: "USD",
    law: "NY",
    couponRate: 0.0725,
    couponFrequency: 2,
    firstCouponDate: "2024-06-15",
    maturityDate: "2031-06-15",
    amortizationType: "bullet",
    minDenomination: 1000,
    creditRating: "AA(arg)",
  },
  {
    ticker: "PNDC6",
    issuer: "Pan American Energy",
    currency: "USD",
    law: "ARG",
    couponRate: 0.0795,
    couponFrequency: 2,
    firstCouponDate: "2024-06-30",
    maturityDate: "2027-12-30",
    amortizationType: "equal",
    amortStartDate: "2026-06-30",
    amortPayments: 4,
    minDenomination: 1,
    creditRating: "AA(arg)",
  },
  {
    ticker: "TLC1O",
    issuer: "Telecom Argentina",
    currency: "USD",
    law: "NY",
    couponRate: 0.08,
    couponFrequency: 2,
    firstCouponDate: "2024-01-18",
    maturityDate: "2031-07-18",
    amortizationType: "bullet",
    minDenomination: 1000,
    creditRating: "AA(arg)",
  },
  {
    ticker: "TLCMO",
    issuer: "Telecom Argentina",
    currency: "USD",
    law: "ARG",
    couponRate: 0.0925,
    couponFrequency: 2,
    firstCouponDate: "2024-05-06",
    maturityDate: "2027-11-06",
    amortizationType: "equal",
    amortStartDate: "2026-05-06",
    amortPayments: 4,
    minDenomination: 1,
    creditRating: "AA(arg)",
  },
  {
    ticker: "IRCP6",
    issuer: "IRSA Propiedades Comerciales",
    currency: "USD",
    law: "ARG",
    couponRate: 0.07,
    couponFrequency: 2,
    firstCouponDate: "2024-09-13",
    maturityDate: "2028-03-13",
    amortizationType: "equal",
    amortStartDate: "2026-09-13",
    amortPayments: 4,
    minDenomination: 1,
    creditRating: "A+(arg)",
  },
  {
    ticker: "ARC1O",
    issuer: "Arcor S.A.I.C.",
    currency: "USD",
    law: "ARG",
    couponRate: 0.065,
    couponFrequency: 2,
    firstCouponDate: "2024-04-07",
    maturityDate: "2027-10-07",
    amortizationType: "equal",
    amortStartDate: "2026-04-07",
    amortPayments: 4,
    minDenomination: 1,
    creditRating: "AA+(arg)",
  },
  {
    ticker: "MRCAO",
    issuer: "Mastellone Hnos.",
    currency: "USD",
    law: "ARG",
    couponRate: 0.075,
    couponFrequency: 2,
    firstCouponDate: "2024-07-05",
    maturityDate: "2028-01-05",
    amortizationType: "equal",
    amortStartDate: "2026-07-05",
    amortPayments: 4,
    minDenomination: 1,
    creditRating: "A(arg)",
  },
  {
    ticker: "GNCXO",
    issuer: "Genneia S.A.",
    currency: "USD",
    law: "NY",
    couponRate: 0.085,
    couponFrequency: 2,
    firstCouponDate: "2024-01-15",
    maturityDate: "2030-01-15",
    amortizationType: "bullet",
    minDenomination: 1000,
    creditRating: "A(arg)",
  },
  {
    ticker: "AECO1",
    issuer: "Petrolera Aconcagua Energía",
    currency: "USD",
    law: "ARG",
    couponRate: 0.09,
    couponFrequency: 2,
    firstCouponDate: "2024-08-15",
    maturityDate: "2027-08-15",
    amortizationType: "equal",
    amortStartDate: "2026-02-15",
    amortPayments: 4,
    minDenomination: 1,
    creditRating: "A-(arg)",
  },
  {
    ticker: "VSCO2",
    issuer: "Vista Energy",
    currency: "USD",
    law: "NY",
    couponRate: 0.075,
    couponFrequency: 2,
    firstCouponDate: "2024-04-15",
    maturityDate: "2032-04-15",
    amortizationType: "bullet",
    minDenomination: 1000,
    creditRating: "A(arg)",
  },
  {
    ticker: "CRES1",
    issuer: "Cresud S.A.",
    currency: "USD",
    law: "ARG",
    couponRate: 0.07,
    couponFrequency: 2,
    firstCouponDate: "2024-10-15",
    maturityDate: "2028-04-15",
    amortizationType: "equal",
    amortStartDate: "2026-10-15",
    amortPayments: 4,
    minDenomination: 1,
    creditRating: "A(arg)",
  },
  {
    ticker: "GMCQO",
    issuer: "Pampa Energía",
    currency: "USD",
    law: "NY",
    couponRate: 0.075,
    couponFrequency: 2,
    firstCouponDate: "2024-01-24",
    maturityDate: "2031-01-24",
    amortizationType: "bullet",
    minDenomination: 1000,
    creditRating: "A+(arg)",
  },
  {
    ticker: "LECAO",
    issuer: "Ledesma S.A.",
    currency: "USD",
    law: "ARG",
    couponRate: 0.068,
    couponFrequency: 2,
    firstCouponDate: "2024-05-20",
    maturityDate: "2028-05-20",
    amortizationType: "equal",
    amortStartDate: "2026-11-20",
    amortPayments: 4,
    minDenomination: 1,
    creditRating: "A+(arg)",
  },
  {
    ticker: "MTCGO",
    issuer: "Ternium Argentina",
    currency: "USD",
    law: "ARG",
    couponRate: 0.065,
    couponFrequency: 2,
    firstCouponDate: "2024-08-09",
    maturityDate: "2027-08-09",
    amortizationType: "equal",
    amortStartDate: "2026-02-09",
    amortPayments: 4,
    minDenomination: 1,
    creditRating: "AA(arg)",
  },
  {
    ticker: "CS38O",
    issuer: "Central Puerto",
    currency: "USD",
    law: "NY",
    couponRate: 0.07,
    couponFrequency: 2,
    firstCouponDate: "2024-06-15",
    maturityDate: "2031-06-15",
    amortizationType: "bullet",
    minDenomination: 1000,
    creditRating: "A+(arg)",
  },
];

async function main() {
  console.log("Seeding corporate bonds...");

  for (const bond of CORPORATE_BONDS) {
    await prisma.bond.upsert({
      where: { ticker: bond.ticker },
      update: {
        issuer: bond.issuer,
        currency: bond.currency,
        law: bond.law,
        couponRate: bond.couponRate,
        couponFrequency: bond.couponFrequency,
        firstCouponDate: new Date(bond.firstCouponDate),
        maturityDate: new Date(bond.maturityDate),
        amortizationType: bond.amortizationType,
        amortStartDate: bond.amortStartDate ? new Date(bond.amortStartDate) : null,
        amortPayments: bond.amortPayments || null,
        minDenomination: bond.minDenomination,
        creditRating: bond.creditRating,
      },
      create: {
        ticker: bond.ticker,
        issuer: bond.issuer,
        currency: bond.currency,
        law: bond.law,
        couponRate: bond.couponRate,
        couponFrequency: bond.couponFrequency,
        firstCouponDate: new Date(bond.firstCouponDate),
        maturityDate: new Date(bond.maturityDate),
        amortizationType: bond.amortizationType,
        amortStartDate: bond.amortStartDate ? new Date(bond.amortStartDate) : null,
        amortPayments: bond.amortPayments || null,
        minDenomination: bond.minDenomination,
        creditRating: bond.creditRating,
      },
    });
    console.log(`  ✓ ${bond.ticker} - ${bond.issuer}`);
  }

  console.log(`\nSeeded ${CORPORATE_BONDS.length} corporate bonds.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
